### ISSUE TITLE
Figure caption conventions

### ISSUE THREAD

**Issue by mbkranz** [HEAL/platform-documentation#3]
Currently, severaly of the figure captions are in html convention. Looks like there are several "figure caption" plugins" but mkdoc-material recommends going with the html-like syntax. https://squidfunk.github.io/mkdocs-material/reference/images/#image-captions

Should we use plugin, have a different work around, or continue to use mkdoc-material recommendation?

**Comment by hughestr** [comment]
Aligned on this convention.
